### ISSUE TITLE
water temps (pool and spa) are not published

### ISSUE THREAD

**Issue by gavc1** [crsherman/nodejs-poolController-mqtt#1]
Testing this plugin I get the following topics published
pool/circuit/
pool/poolheat/
pool/spaheat/

Within the topics above I can see the mode and set temp are published, but the current temperature is not.
I do see it in the console log 
outputSocketToMQTT: Temperature info as follows: {"temperature":{"poolTemp":35,"spaTemp":35,"airTemp":32,"solarTemp":0,"freeze":0,"poolSetPoint":26,"poolHeatMode":0,"poolHeatModeStr":"OFF","spaSetPoint":35,"spaManualHeatMode":"Off","spaHeatMode":1,"spaHeatModeStr":"Heater","heaterActive":1}}

But cannot find anywhere in outputSocketToMQTT.js where you publish the temperature

**Comment by crsherman** [comment]
Gavc1,
Since I mainly use MQTT for the ability to control my pool equipment from node-red, I am not publishing  the temperatures (air and water) using my plugin.  I use the nodejs-poolController api to request the temperatures for air and water to feed into my node-red graph.  See the readme for nodejs-poolController - APIs section for more info.

If you are still interested in a MQTT solution, I could easily add the code to it when I have a few minutes to get to it.  Let me know if you are still interested in lieu of the API.

**Comment by crsherman** [comment]
Issue closed with version 1.1.
